name: ESLint

on:
  workflow_dispatch:
  push:

jobs:
  lint:
    name: ESLint
    runs-on: ubuntu-latest
    steps:
      - name: "☁️ checkout repository"
        uses: actions/checkout@v6

      - name: "🔧 setup node"
        uses: actions/setup-node@v4
        with:
          node-version: 21
          cache: "npm"

      - name: "🛸 install ESLint plugins"
        run: npm i --omit=optional --include=dev --no-fund --progress=false

      - name: "🔍 lint code"
        run: npx eslint .
